export enum STAGE_MEDIA_KEY_TYPES {
  MAIN_IMAGE = 'MAIN_IMAGE',
  SUPPLEMENTARY_IMAGE = 'SUPPLIMENTARY_IMAGE',
  ELEVATION_GRAPH_IMAGE = 'ELEVATION_GRAPH_IMAGE',
}

export enum STAGE_MEDIA_TYPES {
  PHOTO = 'PHOTO',
  VIDEO = 'VIDEO',
}
